base_images:
  base:
    name: "4.6"
    namespace: ocp
    tag: base
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.13
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tag_specification:
  name: "4.6"
  namespace: ocp
tests:
- as: e2e-tests
  commands: make generate
  openshift_installer_src:
    cluster_profile: azure4
zz_generated_metadata:
  branch: ocp-ci-integration
  org: kubevirt
  repo: common-templates
